# Generated by Django 4.0.2 on 2022-03-05 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=120)),
                ('address_line_2', models.CharField(blank=True, max_length=120, null=True)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(default='INDIA', max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('postal_code', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('colour', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('age', models.CharField(choices=[('0 to 14', 'Below 14'), ('15 to 23', '15 to 23'), ('24 to 36', '24 to 36'), ('36+', 'Above 36')], max_length=8)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('O', 'Other')], max_length=1)),
                ('email', models.EmailField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('billingAddress', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='cycleStoreApp.address')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='static')),
                ('featured', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UniqueProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profitPerItem', models.DecimalField(decimal_places=2, default=1000, max_digits=20)),
                ('sales', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=4999, max_digits=20)),
                ('quantity', models.PositiveIntegerField(default=50)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleStoreApp.colour')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleStoreApp.product')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cycleStoreApp.type')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('shipment', 'Shipment Scheduled'), ('shipped', 'Shipped'), ('delivered', 'Out for Delivery'), ('cancelled', 'Cancel')], max_length=15)),
                ('transactionID', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cycleStoreApp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cycleStoreApp.uniqueproduct')),
                ('shippingAddress', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cycleStoreApp.address')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=100)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, to='cycleStoreApp.Product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cycleStoreApp.customer')),
            ],
        ),
    ]
